# This script should be run below the repo src directory.
../src/scripts/filter_jh_data.py admin2-locations --country US --state AK > src/config/us_counties/AK.admin2 > src/config/us_counties/AK.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state AL > src/config/us_counties/AL.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state AR > src/config/us_counties/AR.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state AS > src/config/us_counties/AS.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state AZ > src/config/us_counties/AZ.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state CA > src/config/us_counties/CA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state CO > src/config/us_counties/CO.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state CP > src/config/us_counties/CP.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state CT > src/config/us_counties/CT.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state DC > src/config/us_counties/DC.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state DE > src/config/us_counties/DE.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state FL > src/config/us_counties/FL.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state GA > src/config/us_counties/GA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state GU > src/config/us_counties/GU.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state HI > src/config/us_counties/HI.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state IA > src/config/us_counties/IA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state ID > src/config/us_counties/ID.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state IL > src/config/us_counties/IL.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state IN > src/config/us_counties/IN.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state KS > src/config/us_counties/KS.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state KY > src/config/us_counties/KY.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state LA > src/config/us_counties/LA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state MA > src/config/us_counties/MA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state MD > src/config/us_counties/MD.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state ME > src/config/us_counties/ME.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state MI > src/config/us_counties/MI.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state MN > src/config/us_counties/MN.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state MO > src/config/us_counties/MO.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state MS > src/config/us_counties/MS.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state MT > src/config/us_counties/MT.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state NC > src/config/us_counties/NC.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state ND > src/config/us_counties/ND.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state NE > src/config/us_counties/NE.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state NH > src/config/us_counties/NH.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state NJ > src/config/us_counties/NJ.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state NM > src/config/us_counties/NM.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state NV > src/config/us_counties/NV.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state NY > src/config/us_counties/NY.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state OH > src/config/us_counties/OH.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state OK > src/config/us_counties/OK.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state OR > src/config/us_counties/OR.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state PA > src/config/us_counties/PA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state PR > src/config/us_counties/PR.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state RI > src/config/us_counties/RI.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state SC > src/config/us_counties/SC.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state SD > src/config/us_counties/SD.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state TN > src/config/us_counties/TN.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state TX > src/config/us_counties/TX.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state UT > src/config/us_counties/UT.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state VA > src/config/us_counties/VA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state VI > src/config/us_counties/VI.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state VT > src/config/us_counties/VT.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state WA > src/config/us_counties/WA.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state WI > src/config/us_counties/WI.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state WV > src/config/us_counties/WV.admin2
../src/scripts/filter_jh_data.py admin2-locations --country US --state WY > src/config/us_counties/WY.admin2

