#!/usr/bin/env python3

import re
import sys

us_postal_codes = set([
    'AK',
    'AL',
    'AR',
    'AS',
    'AZ',
    'CA',
    'CO',
    'CP',
    'CT',
    'DC',
    'DE',
    'FL',
    'GA',
    'GU',
    'HI',
    'IA',
    'ID',
    'IL',
    'IN',
    'KS',
    'KY',
    'LA',
    'MA',
    'MD',
    'ME',
    'MI',
    'MN',
    'MO',
    'MS',
    'MT',
    'NC',
    'ND',
    'NE',
    'NH',
    'NJ',
    'NM',
    'NV',
    'NY',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'SS',  # Cruise Ship
    'TN',
    'TX',
    'US',
    'UT',
    'VA',
    'VI',
    'Vt',
    'VT',
    'WA',
    'WI',
    'WV',
    'WY',
])


us_state_names_to_state = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Cruise Ship': 'SS',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands': 'CP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Recovered': 'ZZ',  # If found, probably data entry error.
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'U.S. Virgin Islands': 'VI',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
    'Unknown': 'XX',
    'Unspecified': 'US',
}

us_locations_to_state = {
    'Norfolk County, MA': 'MA',
    'Alabama': 'AL',
    'Alameda County, CA': 'CA',
    'Alaska': 'AK',
    'American Samoa': '',
    'Arizona': 'AZ',
    'Arkansas': 'AK',
    'Ashland, NE': 'NE',
    'Bennington County, VT': 'VT',
    'Bergen County, NJ': 'NJ',
    'Berkeley, CA': 'CA',
    'Berkshire County, MA': 'MA',
    'Boston, MA': 'MA',
    'Broward County, FL': 'FL',
    'California': 'CA',
    'Carver County, MN': 'MN',
    'Charleston County, SC': 'SC',
    'Charlotte County, FL': 'FL',
    'Chatham County, NC': 'NC',
    'Cherokee County, GA': 'GA',
    'Chicago': 'IL',
    'Chicago, IL': 'IL',
    'Clark County, NV': 'NV',
    'Clark County, WA': 'WA',
    'Cobb County, GA': 'GA',
    'Collin County, TX': 'TX',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Contra Costa County, CA': 'CA',
    'Cook County, IL': 'IL',
    'Davidson County, TN': 'TN',
    'Davis County, UT': 'UT',
    'Delaware': 'DE',
    'Delaware County, PA': 'PA',
    'Denver County, CO': 'CO',
    'Diamond Princess': 'SS',
    'District of Columbia': 'DC',
    'Douglas County, CO': 'CO',
    'Douglas County, NE': 'NE',
    'Douglas County, OR': 'OR',
    'El Paso County, CO': 'CO',
    'Fairfax County, VA': '',
    'Fairfield County, CT': 'CT',
    'Fayette County, KY': 'KY',
    'Florida': 'FL',
    'Floyd County, GA': 'GA',
    'Fort Bend County, TX': 'TX',
    'Fresno County, CA': 'CA',
    'Fulton County, GA': 'GA',
    'Georgia': 'GA',
    'Grafton County, NH': 'NH',
    'Grand Princess': 'SS',
    'Grand Princess Cruise Ship': 'SS',
    'Grant County, WA': 'WA',
    'Guam': 'GU',
    'Harford County, MD': 'MD',
    'Harris County, TX': 'TX',
    'Harrison County, KY': 'KY',
    'Hawaii': 'HI',
    'Hendricks County, IN': 'IN',
    'Hillsborough, FL': 'FL',
    'Honolulu County, HI': 'HI',
    'Hudson County, NJ': 'NJ',
    'Humboldt County, CA': 'CA',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Jackson County, OR': 'OR',
    'Jefferson County, KY': 'KY',
    'Jefferson County, WA': 'WA',
    'Jefferson Parish, LA': 'LA',
    'Johnson County, IA': 'IA',
    'Johnson County, KS': 'KS',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Kershaw County, SC': 'SC',
    'King County, WA': 'WA',
    'Kittitas County, WA': 'WA',
    'Klamath County, OR': 'OR',
    'Lackland, TX': 'TX',
    'Lackland, TX (From Diamond Princess)': 'TX',
    'Lee County, FL': 'FL',
    'Los Angeles, CA': 'CA',
    'Louisiana': 'LA',
    'Madera County, CA': 'CA',
    'Madison, WI': 'WI',
    'Maine': 'ME',
    'Manatee County, FL': 'FL',
    'Maricopa County, AZ': 'AZ',
    'Marion County, IN': 'IN',
    'Marion County, OR': 'OR',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Middlesex County, MA': 'MA',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Montgomery County, MD': 'MD',
    'Montgomery County, PA': 'PA',
    'Montgomery County, TX': 'TX',
    'Nassau County, NY': 'NY',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'New York City, NY': 'NY',
    'New York County, NY': 'NY',
    'Norfolk County, MA': 'MA',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands': 'CP',
    'Norwell County, MA': 'MA',
    'Ohio': 'OH',
    'Okaloosa County, FL': 'FL',
    'Oklahoma': 'OK',
    'Omaha, NE (From Diamond Princess)': 'NE',
    'Orange County, CA': 'CA',
    'Orange, CA': 'CA',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Pierce County, WA': 'WA',
    'Pinal County, AZ': 'AZ',
    'Placer County, CA': 'CA',
    'Plymouth County, MA': 'MA',
    'Polk County, GA': '',
    'Portland, OR': '',
    'Providence County, RI': '',
    'Providence, RI': '',
    'Puerto Rico': '',
    'Queens County, NY': '',
    'Ramsey County, MN': '',
    'Recovered': 'ZZ',
    'Rhode Island': 'RI',
    'Riverside County, CA': 'CA',
    'Rockingham County, NH': 'NH',
    'Rockland County, NY': 'NY',
    'Sacramento County, CA': 'CA',
    'San Antonio, TX': 'TX',
    'San Benito, CA': 'CA',
    'San Diego County, CA': 'CA',
    'San Francisco County, CA': 'CA',
    'San Mateo, CA': 'CA',
    'Santa Clara County, CA': 'CA',
    'Santa Clara, CA': 'CA',
    'Santa Cruz County, CA': 'CA',
    'Santa Rosa County, FL': 'FL',
    'Sarasota, FL': 'FL',
    'Saratoga County, NY': 'NY',
    'Seattle, WA': 'WA',
    'Shasta County, CA': 'CA',
    'Shelby County, TN': 'TN',
    'Snohomish County, WA': 'WA',
    'Sonoma County, CA': 'CA',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Spartanburg County, SC': 'SC',
    'Spokane County, WA': 'WA',
    'St. Louis County, MO': 'MO',
    'Suffolk County, MA': 'MA',
    'Suffolk County, NY': 'NY',
    'Summit County, CO': 'CO',
    'Tempe, AZ': 'AZ',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Travis, CA': 'CA',
    'Travis, CA (From Diamond Princess)': 'CA',
    'Tulsa County, OK': 'OK',
    'US': 'US',
    'Ulster County, NY': 'US',
    'Umatilla, OR': 'OR',
    'Unassigned Location (From Diamond Princess)': 'SS',
    'Unassigned Location, VT': 'VT',
    'Unassigned Location, WA': 'WA',
    'United States Virgin Islands': 'VI',
    'Unknown Location, MA': 'MA',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virgin Islands, U.S.': 'VI',
    'Virginia': 'VA',
    'Volusia County, FL': 'FL',
    'Wake County, NC': 'NC',
    'Washington': 'WA',
    'Washington County, OR': 'OR',
    'Washington, D.C.': 'DC',
    'Washoe County, NV': 'NV',
    'Wayne County, PA': 'PA',
    'West Virginia': 'WV',
    'Westchester County, NY': 'NY',
    'Williamson County, TN': 'TN',
    'Wisconsin': 'WI',
    'Wuhan Evacuee': 'ZZ',
    'Wyoming': 'WY',
    'Yolo County, CA': 'CA',
}


us_states_to_state_names = {v: k for k, v in us_state_names_to_state.items()}


def convert_us_location_to_state(location):
    location = location.strip()

    if location.upper() in us_postal_codes:
        return location

    match = re.search(r',\s*(?P<USPS>[A-Z][A-Z])$', location, re.I)
    if match and match.group('USPS') in us_postal_codes:
        postal_code = match.group('USPS')
        # Use Northen Marianas Island USPS code instead of coast guard code.
        if postal_code == 'CM':
            postal_code = 'MP'
        return match.group('USPS')

    if location in us_state_names_to_state:
        return us_state_names_to_state[location]

    if location in us_locations_to_state:
        if us_locations_to_state[location]:
            return us_locations_to_state[location]

    print('unknown US location: "{}"'.format(location))
    return 'XX'


def main():
    for arg in sys.argv[1:]:
        print('"{}": "{}"'.format(arg, convert_us_location_to_state(arg)))


if __name__ == '__main__':
    main()
